spring.application.name=postService

spring.datasource.url=  jdbc:postgresql://localhost:5432/Sphere-postDB
spring.datasource.username=postgres
spring.datasource.password=data@2601
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true


server.port=9010