spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/HEYDEV001/Sphere-Config-server
          username: ${GIT_USERNAME}
          password: ${GIT_TOKEN}
          default-label: master

server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/  # fix localhost → discovery-server



